version: "3.9"

services:
  bbapi:
    build: .
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - DB_DATABASE=bbapi
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_SYNCHRONIZE=true
      - DB_TYPE=postgres
    env_file:
      - .env
    volumes:
      - /bbapi/node_modules
      - /bbapi/.yarn-cache
    depends_on: 
      - redis
      - db
    ports:
      - 9222:9222
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bbapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres